{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "\n",
    "\n",
    "class Porter:\n",
    "    PERFECTIVEGROUND = re.compile(u\"((ив|ивши|ившись|ыв|ывши|ывшись)|((?<=[ая])(в|вши|вшись)))$\")\n",
    "    REFLEXIVE = re.compile(u\"(с[яь])$\")\n",
    "    ADJECTIVE = re.compile(u\"(ее|ие|ые|ое|ими|ыми|ей|ий|ый|ой|ем|им|ым|ом|его|ого|ему|ому|их|ых|ую|юю|ая|яя|ою|ею)$\")\n",
    "    PARTICIPLE = re.compile(u\"((ивш|ывш|ующ)|((?<=[ая])(ем|нн|вш|ющ|щ)))$\")\n",
    "    VERB = re.compile(\n",
    "        u\"((ила|ыла|ена|ейте|уйте|ите|или|ыли|ей|уй|ил|ыл|им|ым|ен|ило|ыло|ено|ят|ует|уют|ит|ыт|ены|ить|ыть|ишь|ую|ю)|((?<=[ая])(ла|на|ете|йте|ли|й|л|ем|н|ло|но|ет|ют|ны|ть|ешь|нно)))$\")\n",
    "    NOUN = re.compile(\n",
    "        u\"(а|ев|ов|ие|ье|е|иями|ями|ами|еи|ии|и|ией|ей|ой|ий|й|иям|ям|ием|ем|ам|ом|о|у|ах|иях|ях|ы|ь|ию|ью|ю|ия|ья|я)$\")\n",
    "    RVRE = re.compile(u\"^(.*?[аеиоуыэюя])(.*)$\")\n",
    "    DERIVATIONAL = re.compile(u\".*[^аеиоуыэюя]+[аеиоуыэюя].*ость?$\")\n",
    "    DER = re.compile(u\"ость?$\")\n",
    "    SUPERLATIVE = re.compile(u\"(ейше|ейш)$\")\n",
    "    I = re.compile(u\"и$\")\n",
    "    P = re.compile(u\"ь$\")\n",
    "    NN = re.compile(u\"нн$\")\n",
    "\n",
    "    def stem(word):\n",
    "        word = word.lower()\n",
    "        word = word.replace(u'ё', u'е')\n",
    "        m = re.match(Porter.RVRE, word)\n",
    "        if m and m.groups():\n",
    "            pre = m.group(1)\n",
    "            rv = m.group(2)\n",
    "            temp = Porter.PERFECTIVEGROUND.sub('', rv, 1)\n",
    "            if temp == rv:\n",
    "                rv = Porter.REFLEXIVE.sub('', rv, 1)\n",
    "                temp = Porter.ADJECTIVE.sub('', rv, 1)\n",
    "                if temp != rv:\n",
    "                    rv = temp\n",
    "                    rv = Porter.PARTICIPLE.sub('', rv, 1)\n",
    "                else:\n",
    "                    temp = Porter.VERB.sub('', rv, 1)\n",
    "                    if temp == rv:\n",
    "                        rv = Porter.NOUN.sub('', rv, 1)\n",
    "                    else:\n",
    "                        rv = temp\n",
    "            else:\n",
    "                rv = temp\n",
    "\n",
    "            rv = Porter.I.sub('', rv, 1)\n",
    "\n",
    "            if re.match(Porter.DERIVATIONAL, rv):\n",
    "                rv = Porter.DER.sub('', rv, 1)\n",
    "\n",
    "            temp = Porter.P.sub('', rv, 1)\n",
    "            if temp == rv:\n",
    "                rv = Porter.SUPERLATIVE.sub('', rv, 1)\n",
    "                rv = Porter.NN.sub(u'н', rv, 1)\n",
    "            else:\n",
    "                rv = temp\n",
    "            word = pre + rv\n",
    "        return word\n",
    "\n",
    "    stem = staticmethod(stem)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "\n",
    "def init_alphabet():\n",
    "    alphabet = ['й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э', 'я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', ' ']\n",
    "    return alphabet\n",
    "\n",
    "\n",
    "def clear_text(string, alphabet):\n",
    "    result_line = ''\n",
    "    for i in string:\n",
    "        if i in alphabet:\n",
    "            result_line = result_line + i\n",
    "    return result_line\n",
    "\n",
    "\n",
    "def clear_spaces(string):\n",
    "    prov = 0\n",
    "    result_string = ''\n",
    "    for i in string:\n",
    "        if i == ' ':\n",
    "            prov += 1\n",
    "        else:\n",
    "            prov = 0\n",
    "        if prov <= 1:\n",
    "            result_string = result_string + i\n",
    "    if result_string[len(result_string) - 1] == ' ':\n",
    "        result_string = result_string[:-1]\n",
    "    return result_string\n",
    "\n",
    "\n",
    "def read_from_folder(path_to_train, alphabet):\n",
    "    text_train = []\n",
    "    step = 0\n",
    "    alphabet = init_alphabet()\n",
    "    words = []\n",
    "    train_data = []\n",
    "    files = os.listdir(path_to_train)\n",
    "    for index in range(0, len(files)):\n",
    "        print(files[index])\n",
    "        file = open(path_to_train + files[index], 'r', encoding='utf-8')\n",
    "        for line in file:\n",
    "            if step > 0:\n",
    "                line = line.lower()\n",
    "                line = clear_text(line, alphabet)\n",
    "                word_in_line = line.split(' ')\n",
    "                words.append(word_in_line)\n",
    "            else:\n",
    "                step = 1\n",
    "                text_train.append(line[:-1])\n",
    "        result_list = ''\n",
    "        step = 0\n",
    "        for line in words:\n",
    "            for word in line:\n",
    "                result_list = result_list + (Porter.stem(word)) + ' '\n",
    "        result_list = clear_spaces(result_list)\n",
    "        train_data.append(result_list)\n",
    "    return train_data, text_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Информатика (1).txt\n",
      "Информатика (10).txt\n",
      "Информатика (11).txt\n",
      "Информатика (12).txt\n",
      "Информатика (13).txt\n",
      "Информатика (14).txt\n",
      "Информатика (15).txt\n",
      "Информатика (16).txt\n",
      "Информатика (17).txt\n",
      "Информатика (18).txt\n",
      "Информатика (19).txt\n",
      "Информатика (2).txt\n",
      "Информатика (20).txt\n",
      "Информатика (21).txt\n",
      "Информатика (22).txt\n",
      "Информатика (23).txt\n",
      "Информатика (24).txt\n",
      "Информатика (25).txt\n",
      "Информатика (26).txt\n",
      "Информатика (27).txt\n",
      "Информатика (28).txt\n",
      "Информатика (29).txt\n",
      "Информатика (3).txt\n",
      "Информатика (30).txt\n",
      "Информатика (31).txt\n",
      "Информатика (32).txt\n",
      "Информатика (33).txt\n",
      "Информатика (34).txt\n",
      "Информатика (35).txt\n",
      "Информатика (36).txt\n",
      "Информатика (37).txt\n",
      "Информатика (38).txt\n",
      "Информатика (39).txt\n",
      "Информатика (4).txt\n",
      "Информатика (5).txt\n",
      "Информатика (6).txt\n",
      "Информатика (7).txt\n",
      "Информатика (8).txt\n",
      "Информатика (9).txt\n",
      "Математика (1).txt\n",
      "Математика (10).txt\n",
      "Математика (11).txt\n",
      "Математика (12).txt\n",
      "Математика (13).txt\n",
      "Математика (14).txt\n",
      "Математика (15).txt\n",
      "Математика (16).txt\n",
      "Математика (17).txt\n",
      "Математика (18).txt\n",
      "Математика (19).txt\n",
      "Математика (2).txt\n",
      "Математика (20).txt\n",
      "Математика (21).txt\n",
      "Математика (22).txt\n",
      "Математика (23).txt\n",
      "Математика (24).txt\n",
      "Математика (25).txt\n",
      "Математика (26).txt\n",
      "Математика (27).txt\n",
      "Математика (28).txt\n",
      "Математика (29).txt\n",
      "Математика (3).txt\n",
      "Математика (30).txt\n",
      "Математика (31).txt\n",
      "Математика (32).txt\n",
      "Математика (33).txt\n",
      "Математика (34).txt\n",
      "Математика (35).txt\n",
      "Математика (36).txt\n",
      "Математика (37).txt\n",
      "Математика (38).txt\n",
      "Математика (39).txt\n",
      "Математика (4).txt\n",
      "Математика (5).txt\n",
      "Математика (6).txt\n",
      "Математика (7).txt\n",
      "Математика (8).txt\n",
      "Математика (9).txt\n"
     ]
    }
   ],
   "source": [
    "classes = ['математика', 'информатика']\n",
    "alphabet = init_alphabet()\n",
    "path_to_train = \"C:\\\\тексты\\\\обучение\\\\\"\n",
    "path_to_test = \"C:\\\\тексты\\\\тестирование\\\\\"\n",
    "train_data = read_from_folder(path_to_train, alphabet)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Информатика (40).txt\n",
      "Информатика (41).txt\n",
      "Информатика (42).txt\n",
      "Информатика (43).txt\n",
      "Информатика (44).txt\n",
      "Информатика (45).txt\n",
      "Информатика (46).txt\n",
      "Информатика (47).txt\n",
      "Информатика (48).txt\n",
      "Информатика (49).txt\n",
      "Информатика (50).txt\n",
      "Математика (40).txt\n",
      "Математика (41).txt\n",
      "Математика (42).txt\n",
      "Математика (43).txt\n",
      "Математика (44).txt\n",
      "Математика (45).txt\n",
      "Математика (46).txt\n",
      "Математика (47).txt\n",
      "Математика (48).txt\n",
      "Математика (49).txt\n",
      "Математика (50).txt\n"
     ]
    }
   ],
   "source": [
    "test_data = read_from_folder(path_to_test, alphabet)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "IOPub data rate exceeded.\n",
      "The notebook server will temporarily stop sending output\n",
      "to the client in order to avoid crashing it.\n",
      "To change this limit, set the config variable\n",
      "`--NotebookApp.iopub_data_rate_limit`.\n",
      "\n",
      "Current values:\n",
      "NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)\n",
      "NotebookApp.rate_limit_window=3.0 (secs)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(train_data[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\stas\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\sklearn\\linear_model\\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'информатика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика', 'математика']\n",
      "['математика' 'математика' 'математика' 'математика' 'математика'\n",
      " 'математика' 'информатика' 'информатика' 'математика' 'информатика'\n",
      " 'информатика' 'математика' 'математика' 'математика' 'математика'\n",
      " 'математика' 'математика' 'математика' 'математика' 'математика'\n",
      " 'математика' 'математика']\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAVoAAAD4CAYAAACt8i4nAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy86wFpkAAAACXBIWXMAAAsTAAALEwEAmpwYAAAZAElEQVR4nO3de5xdVX338c93EjCgJIQCEUnCXVquQbEIqOVinyJXa8EiglyeECkixYpWa8uloFhseapGpOESrk9bErByiVEeLgIqMYGEcImYAEICIUFF5BIISX7PH3tNOA6TzDp7zp7Z5+T7zmu/Zp99zqz9m8yZ36z57bXWVkRgZmbV6RrsAMzMOp0TrZlZxZxozcwq5kRrZlYxJ1ozs4oNrfoEV89a6GEN9hZX3LtwsEOwGrrrjH3U3zY22OO07JyzbPbEfp8vh3u0ZmYVq7xHa2Y2oFS//qMTrZl1lq4hgx3BWzjRmlln0YCUXZviRGtmncWlAzOzirlHa2ZWMfdozcwq5h6tmVnFPOrAzKxiLh2YmVXMpQMzs4q5R2tmVjEnWjOzig3xxTAzs2q5RmtmVrEalg7qF5GZWX9I+VufTekKSUslPdxwbBNJt0manz6O7KsdJ1oz6yzqyt/6diVwUI9jXwJuj4gdgNvT47VyojWzztLCHm1E3A38tsfhI4Cr0v5VwEf7asc1WjPrLE1MwZU0AZjQcGhSREzq49NGRcRigIhYLGnzvs7jRGtmnaWJi2EpqfaVWPvNpQMz6ywtLB2swRJJWxSn0hbA0r4+wYnWzDpLay+G9eYm4Pi0fzzw/b4+waUDM+ssLRxHK+k/gf2ATSUtAs4Gvg5cL+l/A08DR/XVjhOtmXWWFq5HGxGfWMNTBzbTjhOtmXUWT8E1M6tYDafgOtGaWWdxj9bMrFpyojUzq5YTrZlZxdTlRGtmVin3aM3MKuZEa2ZWMSdaM7Oq1S/POtGaWWdxj9bMrGJdXZ4ZZmZWKfdozcyqVr8860RrZp3FPVozs4o50ZqZVcxTcM3MKuYerZlZxZxozcwq5kRrZlYxJ1ozs6rVL8860ZpZZ/EUXDOzirl0YGZWtfrlWSfagbJq1Uqu+MdT2Wjkpvz1F7462OFYDYwZOYyzD95x9eMthr+NyfctZOrsxYMYVftzj3YdNnP699j0XWN5fdmrgx2K1cTCF15j/HUPAtAlmDp+T+5Z8NtBjqr91THR1q9q3IF+/5vnWTBnBuP2P3iwQ7Gaes+YETzz4msseen1wQ6l7UnK3gZKVo9W0g7ABcBOwLDu4xGxbUVxdZTbrrmYAz5xMsvdm7U1OGDHTbnjsV8PdhgdoY5rHeT2aCcD3wVWAPsDVwPXrOnFkiZImiVp1p03Xtf/KNvY/AfuY8MRG7PFNu8e7FCspoZ2iX233YS75v9msEPpCG3bowU2iIjbJSkingLOkXQPcHZvL46IScAkgKtnLYzWhNqeFv3yYebf/zMen/NzVryxnNeXvcr3L76AI0798mCHZjWx19Yb88ulr/DCq28MdigdoY412txE+5qkLmC+pNOAZ4DNqwurc+x/9Hj2P3o8AE89Oof7bp3iJGt/4MAdN+N2lw1appV5VtLngPFAAA8BJ0bEa822k1s6OAPYEDgdeC9wHHB8syczsz/0tqFdvHfsCO5Z4LJBq7SqdCBpS4qct2dE7AIMAY4uE1NWjzYiZqbdl4ETUxCjypxwXbbVTuPYaqdxgx2G1cjrK1ZxxH/M7PuFlq2rtRfDhgIbSHqDorP5bKmYcl4k6fJUOuh+fDJwZ5kTmplVSWpme/PCfdomdLcTEc8A/wo8DSwGXoyIH5WJKbd0MB/4vqTdJd0B7AXsU+aEZmZV6upS9hYRkyJiz4ZtUnc7kkYCRwDbAO8C3i7p2FIx5bwoIr4OTAFmABdHxPiI+F2ZE5qZVamZHm0fPgw8GRHPR8QbwI2U7GDmTlj4u7R7J3C+pLEAEXFRmZOamVWlhcO7ngbeL2lDYBlwIDCrTEO5w7s2Sh/vS9tGa3mtmdmgaVWejYgZkqYCD1BM1ppNmh/QrNxRB+eWadzMbKC1cuHviDibNUzMakZu6eCmNQRxeH8DMDNrpRpODMsuHYykKBd8DVhSXThmZv3TtlNwI+KDkg4B/oHigtiFEfH7SiMzMyuhhnk2fz3aiLg1IvYFHgFuk3RmdWGZmZXTtqt3SXqJYlEFKO7I0wXsSTFrwsysNurYo80tHXg4l5m1hRavddASuWsd3FJ1IGZmrdC2pQOKeb5mZrXXtqUDYNvextJ6HK2Z1U3bDu8Cngf+rcpAzMxaoYZ5NjvRvhwRP640EjOzFqjjxbDcRHtBpVGYmbVI25YOIuJ6SbsAOwHDGo5fXVVgZmZltG2ilXQ2sB9Fop0GfAS4F3CiNbNaqWGezZ6CeyTForfPRcSJwO7A2yqLysyspHYeR7ssIlZJWiFpOLAU2LbCuMzMSqljjzY30c6StDFwKXA/xW3Hf15VUGZmZbXtqIOIODXtXiJpOjA8IuZWF5aZWTldNezS5l4M+1BvxyLi7taHZGZWXg3zbHbp4C6Kuz8+R7FMIhTLJjrRmlmttO3wLuAQ4DhgPeA64OaIWFlZVGZmJdWwRJs3vCsifhARxwATgIOBn1UalZlZSV1dyt4GSm6NdjhwDHA4MB84ucqgzMzKEvXr0uaWDp4DHgRuBl4DDpR0YERcVFlkZmYl1LF0kJtoL6S4+LVe2szMaqltL4ZFxDkAkt4eEa9UGpGZWT/UMM9m3zNsb0mPAvPS490lXVxpZGZmJXRJ2duAxZT5un8H/gL4DUBEPAi8ZRKDmdlga9tRBwARsbBH7cPjaM2sdupYOshNtAsl7QOEpPWB00llBDOzOqnjWge5pYNTgM8AWwKLgHHpsZlZraiJrc+2pI0lTZX0C0nzJO1dJqbcHu3YiPhkmROYmQ2kFg/v+iYwPSKOTH/Nb1imkdwe7WVlGjczG2hdyt/WJs2I/RBwOUBELI+I35WJKbdHO1TSSHr0tiPit2VOamZWlWZGE0iaQLGGS7dJETEp7W8LPA9MlrQ7xU0P/rbMXILcRLtjOknjVxD4djZmVjPNlA5SUp20hqeHAu8BPhsRMyR9E/gS8E/NxpSbaB+NiD2abdzMbKC1cHjsImBRRMxIj6dSJNrmY2pZSGZmNdCqu+BGxHMUQ1t3TIcOBB4tE1Nuj7bUkAYzs4HW4lG0nwWuSyMOngBOLNNIbqLdSNL5wE7AsO6DEXFAmZOamVVlSAtrBxExB9izv+3klg6uo5gJtg1wLvArYGZ/T25m1mqtKh20Um6i/aOIuBx4IyJ+HBEnAe+vMC4zs1Kk/G2g5JYO3kgfF0s6BHgWGF1NSGZm5dVxrYPcRHu+pBHA54FvA8OBM6oKysysrBrm2exE+7G0QVGfBfhLinuIrdXHx41pPirreJ8++V8GOwSrozP26XcTbXsrG+B/AU8D11LcqLF+X4mZGTCkjRPtWOAg4DhgCDA5In5QWVRmZiXV8S64WaMOImJVREwDzgNeBU6rNCozs5JatXpXK2X1aNMKNx8FFgDfjIjZVQZlZlZWO9doL6FIsmOA/bq/kIjYraK4zMxKqWPpIDfRblNpFGZmLVLDDm1eoo2Ip6oOxMysFYbWMNNm327czKwd1DDPOtGaWWdp5ym4ZmZtoYZ51onWzDpLO486MDNrC61c+LtVnGjNrKPUMM860ZpZZ1EN17xyojWzjuIerZlZxZxozcwq1s6LypiZtYUhubecHUBOtGbWUTwzzMysYq7RmplVrIYdWidaM+ssXR5Ha2ZWLfdozcwqNrSGRVonWjPrKO7RmplVrI7Du2o4tNfMrDwpf8trT0MkzZZ0S9mY3KM1s45SQe/xb4F5wPCyDbhHa2YdpUvK3voiaTRwCHBZv2LqzyebmdVNM4lW0gRJsxq2CT2a+3fgi8Cq/sTk0oGZdZRmLoVFxCRgUq/tSIcCSyPifkn79ScmJ1oz6ygtHHSwL3C4pIOBYcBwSddGxLHNNuTSgZl1FBUlgaxtbSLiyxExOiK2Bo4G7iiTZME9WjPrMHXsPTrRmllHqWLCQkTcBdxV9vOdaM2so/hWNmZmFXPpwMysYu7RmplVrH5p1onWzDrMEPdozcyqVcM860RrZp1FNSweONGaWUdxj9bMrGK+C66ZWcXcozUzq1gd7xnmRGtmHaWGdxt3ojWzzuJRB2ZmFath5aCW6y90pJ/cczeHH/IXHHrQn3P5pb3eOcPWAZec/Umeuv0CZk35h9XHPvbhPbh/6ld45f5v8Z6dxg5idJ1BTfwbKE60A2DlypV87av/zMWXXMb3brqV6dNu4fEFCwY7LBsE19x8H0d85jt/cOyRx5/l6M9fyr0PPD5IUXWWLuVvA8WlgwHw8ENzGTNmK0aPGQPAQQcfwl133s52228/yJHZQPvJA48zdotN/uDYY08uGaRoOlMdRx24RzsAli5Zwju3eOfqx5uPGsWSJf7hMquCmtgGSlailfR+STMlvSxpuaSVkn6/ltevvle665EQxFuO1XHNTLNO0CVlbwMlt3QwkeIukFOAPYFPAWv8u7fxXumvregly6xjRo16J88tfm7146VLlrD55psPYkRmnauOXZjs0kFELACGRMTKiJgM7F9dWJ1l51125emnf8WiRQt5Y/lypk+7lT/b/4DBDsusM9WwdpDbo31V0vrAHEkXAouBt1cXVmcZOnQoX/7KWfzNhPGsWrWSj/7lX7H99jsMdlg2CK664AQ++N4d2HTjd7Bg+nmcd8k0XnjxFS76+6PYdOQ7uPFbpzD3sWc4vMfIBMtXx4thiuj7L3tJWwFLgPWBzwEjgItTL3etXDqw3ox832mDHYLV0LLZE/udJWc+8WJ2znnftiMGJCvn9mgXRcRK4DXgXABJu1QWlZlZWfXr0GbXaG+RtCGApPUlfRW4qrqwzMzKaeeZYVcBt0k6ApgJLAP2qiwqM7OSpPxtoGSVDiLivyQtBW4EjomIadWGZWZWTg0rB3mJVtK30u4c4ApJ1wNExOkVxWVmVkodJwPlXgy7v8dHM7NaqmGezS4d+MKXmbWFGubZ7NLB3N6OR8RurQ3HzKyfWpRpJY0BrgbeCawCJkXEN8u0lVs6mAvsDJyV9s3MaqmFw7ZWAJ+PiAckbQTcL+m2iHi02YZySwfHpgkK5wMvAWdFxJPNnszMrGqtqtFGxGKK5QaIiJckzQO2BJpOtLnLJG4CPAucBFwPTJE0sdmTmZlVrZlxtI1LuqZtQu9tamtgD2BGmZiaGXXQPX+4+/fFwWVOaGZWpWZKB41Luq6xPekdwA3AGRGxxnW41ya3dLBNmcbNzAZaK4d3SVqPIsleFxE3lm0nt3TwQNkTmJkNpFYtR6ti5sPlwLyIuKg/MeWudVDHoWlmZm/VuoW/9wWOAw6QNCdtpUqmuTXaHXuMpRUQHkdrZnXTqoW/I+JeWtTJzE20TwKHteKEZmZVquOf37mJdnlEPFVpJGZmrVDDTJubaD9baRRmZi0ykAt658od3nWvpEMopuEOazj+z1UFZmZWRtuu3iXpEmBDiluMXwYcCfy8wrjMzEqpYZ7NHt61T0R8CnghIs4F9gbGVBeWmVk5krK3gZJbo12WPr4q6V3AbwDPFjOz2mnb0gHFXXA3Br4BPECx7sFlVQVlZlZWDfNs9sWw89LuDZJuAYZFxIvVhWVmVlINM23uxbBP9XKMiLi69SGZmZXXtsO7gCuB+4BZvPn7Iihu82BmVhvtXKPdGTgRGAdMA66NiF9XFZSZWVldNUy0WcO7ImJeRHyRYr2DnYA7K43KzKy01i3f1Sq569G+W9LXgZuAecABlUZlZlZSM7eyGSi5pYNfUNwrZxbF+Nl/ShfDTq8sMjOzEmpYOchOtCfx5j3DzMxqq20vhkXElZLWB/6YIuE+FhHLK43MzKyEgZxamyt3HO3BwH8Aj1P0zLeR9OmI+EGVwZmZNat+aTa/dHARsH9ELACQtB1wK+BEa2a1UsMObXaiXdqdZJMngKUVxGNm1i/tPDPsEUnTgOsparRHATMlfQygP/c7NzNrqfrl2exEOwxYAvxZevw8sAnFBIYAnGjNrBZqmGezRx2cWHUgZmat0KrbjbdS7syw0ZK+J2mppCWSbpA0uurgzMyaVceZYbm3splMMf32XcCWwM3pmJmZ9SE30W4WEZMjYkXargQ2qzAuM7NS2rlH+2tJx0oakrZjKe4bZmZWK2ri30DJTbQnAR8HnkvbkemYmVmt1LFHmzvq4Gng8IpjMTPrtxoOOsgedbCdpKmSnpa0UNKNkt5ddXBmZs1q59LBVOAqitW73k1xD7EpFcVkZlZaHUsHuYn2BeCHEfFqRCwDfoQvhplZDbXyRjaSDpL0mKQFkr5UNqa11mgl3UwxxXY4MEdS98Iy2wMvS7oJICJcvzWzemhRT1XSEOA7wJ8DiyjWd7kpIh5ttq2+Lob9a/p4KnAvMDc93h3YG7ik2ROamVWphVNw/xRYEBFPAEj6L+AIoOlEq4i+71Aj6cGI2L3hsYA5jcesb5ImRMSkwY7D6sXvi8EjaQIwoeHQpO7vhaQjgYMiYnx6fBywV0Sc1ux5clfvulvSHcAd6fEBwE+aPZkxAfAPlPXk98UgSUl1Tf/3vXWNS907MXcc7Wcl7Qu8L5387Ii4p8wJzczaxCJgTMPj0cCzZRrKvWfYWGBh2lYfSxMZzMw60UxgB0nbAM8ARwPHlGkot3Rwa/q4LW/eoDGA3cqcdB3mPw+tN35f1FBErJB0GvBDYAhwRUQ8UqatrIthq18szY6IPcqcyMxsXZU7YaFbqUKwmdm6LLdG+zGKcsHG3TdkBN+U0cwsR+442skUvdnu2iwAEeGlEm2dI2k/4MyIOHSQQ7E2kXsx7GXeTLTdXEYwM8uQW6M9GPgQ8DAwK233VxVUlSRtLSkknZIeD5H0jKQrJR0maYak2ZL+n6RRkjaQNCdtyyU9lPb3lLRZulHlzLTtm9o8R9IySRunxx9J59wvPf6upFmSHpF0bjr216ndBZJeTPvT0nMvN8R/j6RbGs5zZtr/UvrLA0l/Kumn6ev4qaQdB+i/t22k98HDaX89SU9ImpjeB0c2vO5hSVun/W9LeohiSvoWku6U9KCkHdLzW0m6XdLc9HFsOn6lpEvS9+6Xkg5Nx09I74s/To//JD0+IT0+K72vHpY0SYUPpvfGo+k9NkfSnPT6X0naNO1f2/D1nSBpYto/WtIP09e8dYrpgbTtU/l//LoqIvrcKHq+n6EYVzYe6Mr5vDpuwNbAfGB6enwIcB/F0o8jebOcMh74tx6f+ytg04bH/xf4QNofC8xL++cAM4BT0+P/pPjltF96vEn6OAS4C9itoc39gFt6nPflhljndj+fznMm8CmKIXhD0/HhDfsfBm4Y7P/3um3pffBw2v9M+n+dmN4HRza87uH02g+k71UXcDrwC2ADigXxb0ivvRk4Pu2fBPxP2r8SmJ4+dweKgfDDgBPS++TC9LpvpPfiCY3vk7R/DXBYb/H3fH8CuwJzGr6+E9LXdiDwM2CjdHxDYFja3wGYNdjfl07dsnq0UdyQ8TsUvdrNgJ82/tZvQ68DCyTtDBwHXJuOjwZ+mHotXwB27qOdDwMTU4/iJmC4pI3SczcBh0vaBFiP4hZA3T4u6QFgdjrHTn0FLEnAV4Cv9RLDZcA/RsSKdGwEMCX1aP5PxtexzpK0IXAi8N2Gw99o6Clul469D7gjIlZRJOUFUSwZejuwV3rN3hS/fKFIjB9oaPP6iFgVEfOBJyjWdoai87KHpGHAOIpfyN32T39hPUQx7T33+3g+cHaPY7sC36NI6i+lY+sBl6b2p5DxPrRycu+w8JCkuRS/fY+huO34f1cZ2ACYDHyRorfenQS/DUyMiF2BT1P0OtamC9g7IsalbcuGN/HrFD3nf+HNHz5UzDI5EzgwInaj6In2dR6AT1D0qJ7rcXxb4FjgopSMAc4D7oyIXYDDMttfV51BMWFgWcOxL3R/Tykm6MCaF9/ree2i53O97fd8PJ3ivfeD7gMp8V5M0bveFbiUvO/jPhTXVB7scfxPKH52z01tA3wOWEKxGt+ewPoZ7VsJuTXaQyl+YA9L+x+k+AFvWxFxP7A5RcLtNoJiqh3A8RnN/AhYvZKPpHE9nr8c2IPiT8puw4FXgBcljQI+knGeLoofigt7eW5SRFwPPAmcnI41fh0nZLS/rhoBfBS4IuO1s4ADJHVRzIjcXtIGFH9RzEyv+SnFNE2AT1IsLdrtKEldkraj+Nl5rOG5aygS5LUNx7qT4a8lvYPihqg5zgHO6uX49RFxC8XdUrqfHwEsTr304yhKWVaB3EVlnqo6kMEQER+B1cuhQfEmnSLpGYpa2TZ9NHE68J3U2x8K3A2c0tD+HIqeAt2dzYh4UNJs4BGKPyFzVkHbAJgaEb/Tmtfa/DzwMxWLtV8IXCXp73hzxTV7q9EUw7RWrOX/FYCIuFvSPIqe4qMUvcZpFDXRo9LLTgeukPQF4HmKkkS3x4AfA6OAUyLitYb3xFJSWaDh2O8kXQo8RFF7nUmeGRHxePcFvF5cAPxcxdqqFwM3SDoKuJOiA2AVaGoKrpk1P45W0pUUFzCnVhiW1VizU3DNzKxJ7tGamVXMPVozs4o50ZqZVcyJ1sysYk60ZmYVc6I1M6vY/wdcVgSm0nXneQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "files = os.listdir(path_to_train)\n",
    "cv = TfidfVectorizer()\n",
    "input = cv.fit_transform(train_data[0])\n",
    "model = LogisticRegression(solver='lbfgs',n_jobs=1, C=1e5)\n",
    "model.fit(input, train_data[1])\n",
    "test = cv.transform(test_data[0])\n",
    "scores = model.score(test, test_data[1])\n",
    "print(test_data[1])\n",
    "print(model.predict(test))\n",
    "sns.heatmap(confusion_matrix(test_data[1], model.predict(test)), xticklabels=classes, yticklabels=classes, annot=True, fmt=\"d\",cmap=plt.cm.Blues)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
